[Bot Loadout]
team_color_id = 5
custom_color_id = 0
car_id = 6
decal_id = 1744
wheels_id = 358
boost_id = 32
antenna_id = 6
hat_id = 224
paint_finish_id = 1681
custom_finish_id = 270
engine_audio_id = 1793
trails_id = 1948
goal_explosion_id = 1903

[Bot Loadout Orange]
team_color_id = 5
custom_color_id = 0
car_id = 6
decal_id = 1744
wheels_id = 358
boost_id = 32
antenna_id = 6
hat_id = 224
paint_finish_id = 1681
custom_finish_id = 270
engine_audio_id = 1793
trails_id = 1948
goal_explosion_id = 1903